language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t radu93/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true radu93/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-r3"
  env: "Dockerr3-env"
  bucket_name: "elasticbeanstalk-us-east-2-793564225149"
  bucket_path: "docker-r3"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key: "$AWS_SECRET_KEY"
